#!/system/bin/sh
# =============================================================================
# fix-bt-stack.sh — bring up Bluetooth on a STOCK Samsung ROM running a custom
# GKI kernel (a34x / mt6877).
#
# ROOT CAUSE this fixes:
#   The MediaTek BT driver /vendor/lib/modules/bt_drv_6877.ko needs the generic
#   Bluetooth core (net/bluetooth => bluetooth.ko, CONFIG_BT=m in gki_defconfig)
#   which exports hci_alloc_dev_priv / hci_register_dev / hci_recv_frame / ...
#   bluetooth.ko lives in the GKI system_dlkm partition, NOT in vendor.
#   If it is not loaded, insmod bt_drv_6877.ko fails with:
#       bt_drv_6877: Unknown symbol hci_recv_frame (err -2)
#   -> BT HAL gets fd -1 -> com.android.bluetooth dies -> BT never turns on.
#
# WHAT IT DOES:
#   1. finds bluetooth.ko (system_dlkm / system / vendor / any extra dir given)
#   2. loads it (+ rfcomm/hidp if present)
#   3. loads bt_drv_6877.ko
#   4. optionally installs a KernelSU post-fs-data hook so it happens at boot
#
# USAGE (Termux, root):
#   su
#   sh /sdcard/fix-bt-stack.sh            # test now, no persistence
#   sh /sdcard/fix-bt-stack.sh --persist  # + install boot hook
#   sh /sdcard/fix-bt-stack.sh --persist /sdcard/kernel-modules   # extra .ko dir
# =============================================================================

PERSIST=0
EXTRA_DIR=""
for a in "$@"; do
  case "$a" in
    --persist) PERSIST=1 ;;
    -*) ;;
    *) EXTRA_DIR="$a" ;;
  esac
done

SEARCH_DIRS="$EXTRA_DIR /system_dlkm/lib/modules /system/lib/modules /system/system_dlkm/lib/modules /vendor/lib/modules /odm/lib/modules"
LOG=/data/adb/bt_stack_fix.log

say() { echo "[bt-fix] $*"; }

find_ko() {
  _name="$1"
  for d in $SEARCH_DIRS; do
    [ -n "$d" ] || continue
    [ -d "$d" ] || continue
    _hit=$(find "$d" -name "$_name" 2>/dev/null | head -n 1)
    [ -n "$_hit" ] && { echo "$_hit"; return 0; }
  done
  return 1
}

loaded() { grep -q "^$1 " /proc/modules; }

load_ko() {
  _name="$1"; _mod="${1%.ko}"
  if loaded "$_mod"; then say "$_mod already loaded"; return 0; fi
  _p=$(find_ko "$_name") || { say "$_name NOT FOUND"; return 1; }
  insmod "$_p" 2>&1
  _rc=$?
  if [ $_rc -eq 0 ]; then say "loaded $_p"; else say "insmod $_p FAILED rc=$_rc"; fi
  return $_rc
}

say "kernel: $(uname -r)"

# 1) core stack -------------------------------------------------------------
load_ko rfkill.ko >/dev/null 2>&1
load_ko bluetooth.ko || {
  say "bluetooth.ko could not be loaded -> BT cannot work."
  say "dmesg:"; dmesg | grep -iE "bluetooth|version magic|unknown symbol" | tail -n 20
  exit 1
}
load_ko rfcomm.ko
load_ko hidp.ko

# 2) mediatek bt driver -----------------------------------------------------
load_ko bt_drv_6877.ko

# 3) result -----------------------------------------------------------------
say "modules:"; grep -E "^(bluetooth|rfcomm|hidp|bt_drv|btif_drv|mtk_btcvsd) " /proc/modules
say "/dev/stpbt:"; ls -l /dev/stpbt 2>/dev/null || say "  missing"
say "dmesg:"; dmesg | grep -iE "bluetooth|bt_drv|stpbt|unknown symbol" | tail -n 25

# 4) persistence ------------------------------------------------------------
if [ "$PERSIST" = "1" ]; then
  HOOK_DIR=/data/adb/ksu/post-fs-data.d
  mkdir -p "$HOOK_DIR"
  SELF_COPY=/data/adb/fix-bt-stack.sh
  cat "$0" > "$SELF_COPY"; chmod 0755 "$SELF_COPY"
  cat > "$HOOK_DIR/98-bt-stack.sh" <<EOF
#!/system/bin/sh
# auto-generated by fix-bt-stack.sh
(sleep 5; sh $SELF_COPY ${EXTRA_DIR:+"$EXTRA_DIR"} > $LOG 2>&1) &
EOF
  chmod 0755 "$HOOK_DIR/98-bt-stack.sh"
  say "boot hook installed: $HOOK_DIR/98-bt-stack.sh (log: $LOG)"
fi

say "done. now toggle Bluetooth ON in Settings."
