#!/system/bin/sh
# =============================================================================
# install-modules-ksu.sh — install kernel modules matching a custom kernel
# on a STOCK Samsung ROM, using KernelSU-Next root + a boot script.
#
# WHY: flashing only the kernel Image leaves the ROM with STOCK modules
# (vendor_dlkm) built for the stock kernel -> vermagic/CRC mismatch ->
# wifi / bt / hotspot dead. This installer puts the modules from YOUR
# kernel build into a persistent root location and loads them at every
# boot via /data/adb/ksu/post-fs-data.d/.
#
# Usage (from a PC with adb):
#   # 1) on PC: extract the artifact and push it
#   tar -xJf kernel-modules.tar.xz
#   adb push kernel-modules /data/local/tmp/
#   adb push install-modules-ksu.sh /data/local/tmp/
#   # 2) install (root via KSU)
#   adb shell su -c "sh /data/local/tmp/install-modules-ksu.sh /data/local/tmp/kernel-modules"
#   # 3) reboot and test wifi/bt
#
# It also loads the modules immediately (no reboot needed for a quick test).
# =============================================================================

MODROOT="/data/adb/ksu_modules"
KSU_HOOK_DIR="/data/adb/ksu/post-fs-data.d"
BOOT_SCRIPT="$KSU_HOOK_DIR/99-load-ksu-modules.sh"
LOG="$MODROOT/load.log"

say() { echo "[install] $*"; }

# ---- locate source: a directory or a tar/tar.xz -----------------------------
SRC="${1:-/data/local/tmp/kernel-modules}"
say "source: $SRC"
KO_SRC=""
if [ -d "$SRC" ]; then
  if find "$SRC" -name '*.ko' 2>/dev/null | grep -q .; then
    KO_SRC="$SRC"
  else
    say "ERROR: no .ko files under $SRC"
    exit 1
  fi
elif [ -f "$SRC" ]; then
  TMPX="/data/local/tmp/ksu_modules_x"
  rm -rf "$TMPX"; mkdir -p "$TMPX"
  case "$SRC" in
    *.tar.xz|*.txz)
      if ! tar -xJf "$SRC" -C "$TMPX" 2>/dev/null; then
        say "ERROR: device cannot unpack xz. Extract on PC and push the folder instead."
        exit 1
      fi ;;
    *.tar) tar -xf "$SRC" -C "$TMPX" || { say "ERROR: tar extract failed"; exit 1; } ;;
    *) say "ERROR: unsupported file: $SRC (give a folder or .tar.xz)"; exit 1 ;;
  esac
  KO_SRC="$(find "$TMPX" -name '*.ko' 2>/dev/null | head -n1 | xargs dirname)"
  KO_SRC="$(find "$TMPX" -type d -name modules 2>/dev/null | head -n1)"
  [ -z "$KO_SRC" ] && KO_SRC="$TMPX"
else
  say "ERROR: $SRC not found. Push the modules folder first."
  exit 1
fi
say "module tree: $KO_SRC"

# ---- install into persistent root location ----------------------------------
KVER="$(uname -r)"
DEST="$MODROOT/lib/modules/$KVER"
rm -rf "$DEST"
mkdir -p "$DEST"
find "$KO_SRC" -name '*.ko' -exec cp {} "$DEST/" \; 2>/dev/null
# depmod files if present (modules.dep/alias/softdep...)
for f in modules.dep modules.dep.bb modules.alias modules.softdep modules.load modules.load.recovery modules.order; do
  find "$KO_SRC" -name "$f" -exec cp {} "$DEST/" \; 2>/dev/null
done
N=$(find "$DEST" -name '*.ko' | wc -l)
say "installed $N modules to $DEST"
[ "$N" -eq 0 ] && { say "ERROR: nothing copied"; exit 1; }

# connectivity sanity list
say "connectivity modules present:"
find "$DEST" -name '*.ko' | sed 's/.*\///' | grep -iE "wlan|wmt|conn|bt|cfg80211|mac80211|gps|fm|stp" | sed 's/^/  /'

# ---- the loader (runs now AND at every boot) --------------------------------
cat > "$MODROOT/loader.sh" <<'LOADER'
#!/system/bin/sh
# multi-pass insmod: dependencies resolve across passes; skip already-loaded
# NOTE: module name in /proc/modules can differ from filename for a few
# drivers, so we match on both the filename stem and the .ko's own name
# (modinfo falls back to strings when modinfo is unavailable).
D="$(uname -r)"
DIR="/data/adb/ksu_modules/lib/modules/$D"
LOG="/data/adb/ksu_modules/load.log"
: > "$LOG"
echo "$(date) loading modules from $DIR" >> "$LOG"
modname_of() {
  n="$(modinfo -F name "$1" 2>/dev/null)"
  [ -z "$n" ] && n="$(strings "$1" 2>/dev/null | sed -n 's/^name=//p' | head -n1)"
  [ -z "$n" ] && n="$(basename "$1" .ko)"
  echo "$n"
}
pass=1
while [ $pass -le 6 ]; do
  progress=0
  for k in "$DIR"/*.ko; do
    [ -e "$k" ] || continue
    m="$(modname_of "$k")"
    if grep -q "^$m " /proc/modules 2>/dev/null; then
      continue
    fi
    if insmod "$k" >> "$LOG" 2>&1; then
      echo "OK  $m" >> "$LOG"
      progress=$((progress+1))
    else
      echo "ERR $m ($k)" >> "$LOG"
    fi
  done
  [ $progress -eq 0 ] && break
  pass=$((pass+1))
done
echo "$(date) done (passes=$pass, loadable=$(grep -c '^OK' "$LOG"))" >> "$LOG"
LOADER
chmod 755 "$MODROOT/loader.sh"

# ---- KSU boot hook so modules load at every boot -----------------------------
mkdir -p "$KSU_HOOK_DIR"
cat > "$BOOT_SCRIPT" <<EOF
#!/system/bin/sh
# auto-generated by install-modules-ksu.sh — loads custom kernel modules
sh $MODROOT/loader.sh
EOF
chmod 755 "$BOOT_SCRIPT"
say "boot hook installed: $BOOT_SCRIPT"

# ---- load right now for an immediate test ------------------------------------
say "loading modules now (quick test)..."
sh "$MODROOT/loader.sh"
echo "---- loader log ----"
cat "$LOG" | tail -n 60
echo "---- /proc/modules (connectivity) ----"
grep -iE "wlan|wmt|conn|bt|cfg80211|mac80211|gps|fm|stp" /proc/modules || echo "(none loaded!)"

say "DONE. Reboot once and test WiFi/BT."
say "If still dead: run diag-connectivity.sh and send the output."
